name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress comando line
        default: cypress/e2e/**

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.5

      - name: Cypress Run
        uses: cypress-io/github-action@v6.5.0
        with:
          install command: npm install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{github.event.inputs.spec}}
        env:
          CYPRESS_RECORD_KEY: bb20a932-fdd5-43e0-b6cf-26c74ce41914
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
