name: Cypress Tests in Tesults

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by node command
        default: node runner.js

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.5

      - name: Install Dependencies
        run: npm install

      - name: Run E2E Tests
        run: ${{github.event.inputs.cli}}
